Add tags and author links
arcinech/javascript-blog pull request #3
Opened 2022-02-16 20:28 UTC by arcinech

2022-02-17 16:31 UTC, kamilwilk95 requested changes

2022-02-17 16:31 UTC, kamilwilk95 commented on js/script.js
> +        const tagLink = '<li><a href="#tag-' + tag + '">' + tag + '</a></li>';
Pomiędzy tagami brakuje odstępu

2022-02-17 18:42 UTC, arcinech commented on js/script.js
> +        const tagLink = '<li><a href="#tag-' + tag + '">' + tag + '</a></li>';
Witam. Dodałem whitespace  dla dodania odstępu pomiędzy tagami.

2022-02-18 14:42 UTC, kamilwilk95 approved these changes

2022-02-18 15:06 UTC, merged